
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ushmvfuczmqjjtwnqebp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzaG12ZnVjem1xamp0d25xZWJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyNzUwNzYsImV4cCI6MjA1Njg1MTA3Nn0.XJ-Xt_WOcu1Jbx6qFrMfJ265mPxNFo5dwj0eQb-PUUQ";

// Configure client with optimized options
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true, // Enable session detection in URL
    storageKey: 'supabase.auth.token', // Ensure consistent storage key
  },
  realtime: {
    timeout: 20000,
  },
  global: {
    fetch: (...args: Parameters<typeof fetch>) => fetch(...args),
  },
  db: {
    schema: 'public'
  },
  // Add improved error handling and retry logic
  headers: {
    'X-Client-Info': 'attendance-app-web'
  }
});

// Optimized connection checking utility
export const checkConnection = async (): Promise<boolean> => {
  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 5000);
    
    const { data, error } = await supabase.from('profiles')
      .select('count', { count: 'exact', head: true })
      .abortSignal(controller.signal);
    
    clearTimeout(timeoutId);
    
    if (error) {
      console.error('Connection check failed with error:', error);
      return false;
    }
    
    console.log('Connection check successful');
    return true;
  } catch (error) {
    console.error('Connection check exception:', error);
    return false;
  }
};
